import {
  create,
  NLayout,
  NLayoutHeader,
  NLayoutFooter,
  NLayoutSider,
  NSpace,
  NSwitch,
  NMenu,
  NIcon,
  NButton,
  NInput,
  NTooltip,
  NDrawer,
  NDrawerContent,
  NLayoutContent,
  NDivider,
  NDropdown,
  NPopselect,
  NCard,
  NModal,
  NDataTable,
} from "naive-ui";

export const registerNaiveUI = () => {
  return create({
    components: [
      NLayout,
      NLayoutHeader,
      NLayoutFooter,
      NLayoutSider,
      NSpace,
      NSwitch,
      NMenu,
      NIcon,
      NButton,
      NInput,
      NTooltip,
      NDrawer,
      NDrawerContent,
      NLayoutContent,
      NDivider,
      NDropdown,
      NPopselect,
      NCard,
      NModal,
      NDataTable,
    ],
  });
};
